# -*- coding: utf-8 -*-
"""factorial.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuemWH_7ORDyRtlV35cWTw4VFHJ86kyM
"""

n=5
fact=1
for i in range(1,n+1):
  fact=fact*i
  print(fact)